[Service]
ExecStart=
ExecStart=/usr/bin/systemd-inhibit --what=handle-power-key --who=gwv3-power-button --why=GWV3-five-second-power-key --mode=block /usr/bin/python3 -u /home/cat/wireless_video_delivery/12_apps/recording_buttons/power_button_service.py --config /home/cat/wireless_video_delivery/12_apps/recording_buttons/config_lubancat-local_power.json
