[Service]
Environment=XIAOHUAN_AUDIO_STREAM_ENABLED=1
Environment=XIAOHUAN_AUDIO_STREAM_HOST=192.168.66.32
Environment=XIAOHUAN_AUDIO_STREAM_PORT=50020
Environment=XIAOHUAN_AUDIO_STREAM_SAMPLE_RATE=48000
Environment=XIAOHUAN_AUDIO_STREAM_BITRATE=64000
