#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${GWV3_SENDER_ENV_FILE:-/etc/gwv3/sender.env}"
[[ -r "$ENV_FILE" ]] || {
  echo "GWV3 sender environment is not readable: $ENV_FILE" >&2
  exit 1
}
# The environment file is root-owned and generated by install_sender_service.sh.
source "$ENV_FILE"

: "${GWV3_ROOT:?GWV3_ROOT is required}"
: "${GWV3_CONFIG:?GWV3_CONFIG is required}"
: "${GWV3_RUN_USER:?GWV3_RUN_USER is required}"
GWV3_MODE="${GWV3_MODE:-no-local-preview}"
GWV3_HOME="${GWV3_HOME:-$(getent passwd "$GWV3_RUN_USER" | cut -d: -f6)}"

case "${1:-}" in
  --prepare)
    "$GWV3_ROOT/05_tools/prepare_rk3588_usb.sh"
    if command -v chronyc >/dev/null 2>&1 && systemctl is-active --quiet chrony.service; then
      if ! GEMINI_CHRONY_WAITSYNC_TRIES="${GWV3_CHRONY_STARTUP_TRIES:-10}" \
        GEMINI_CHRONY_WAITSYNC_INTERVAL_S="${GWV3_CHRONY_STARTUP_INTERVAL_S:-1}" \
        "$GWV3_ROOT/05_tools/wait_chrony_sync.sh" \
          "${GWV3_CHRONY_MAX_CORRECTION_S:-0.010}"; then
        echo "GWV3 sender startup warning: chrony has not converged; CLOCK_SYNC must remain invalid until recovery" >&2
      fi
    fi
    ;;
  --run)
    [[ -x "$GWV3_ROOT/05_tools/sender_watchdog.sh" ]] || {
      echo "sender watchdog is not executable under $GWV3_ROOT" >&2
      exit 1
    }
    [[ -r "$GWV3_CONFIG" ]] || {
      echo "sender config is not readable: $GWV3_CONFIG" >&2
      exit 1
    }
    exec /usr/sbin/runuser -u "$GWV3_RUN_USER" -- \
      /usr/bin/env HOME="$GWV3_HOME" \
      "$GWV3_ROOT/05_tools/sender_watchdog.sh" "$GWV3_CONFIG" "$GWV3_MODE"
    ;;
  *)
    echo "usage: $0 --prepare|--run" >&2
    exit 2
    ;;
esac
